"""initial_phase_1_2

Revision ID: 2518ca5bec17
Revises: 
Create Date: 2026-05-15 13:00:01.399467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2518ca5bec17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('telegram_id', sa.String(), nullable=True),
        sa.Column('wallet_address', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('plan', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('telegram_id'),
        sa.UniqueConstraint('username'),
        sa.UniqueConstraint('wallet_address')
    )
    op.create_table('paper_accounts',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('initial_balance', sa.DECIMAL(precision=18, scale=8), nullable=True),
        sa.Column('current_balance', sa.DECIMAL(precision=18, scale=8), nullable=True),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_accounts_user_id'), 'paper_accounts', ['user_id'], unique=False)
    op.create_table('payments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('plan', sa.String(), nullable=False),
        sa.Column('amount', sa.DECIMAL(precision=18, scale=8), nullable=True),
        sa.Column('currency', sa.String(), nullable=True),
        sa.Column('provider', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('preferences',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'key', name='uix_user_preference_key')
    )
    op.create_index(op.f('ix_preferences_key'), 'preferences', ['key'], unique=False)
    op.create_index(op.f('ix_preferences_user_id'), 'preferences', ['user_id'], unique=False)
    op.create_table('referrals',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('referrer_id', sa.String(), nullable=False),
        sa.Column('referred_id', sa.String(), nullable=True),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('reward_amount', sa.DECIMAL(precision=18, scale=8), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('converted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['referred_id'], ['users.id']),
        sa.ForeignKeyConstraint(['referrer_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('favorites',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('instrument_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'instrument_id', name='uix_user_favorite')
    )
    op.create_index(op.f('ix_favorites_instrument_id'), 'favorites', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('performance_snapshots',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('total_trades', sa.Integer(), nullable=True),
        sa.Column('winning_trades', sa.Integer(), nullable=True),
        sa.Column('losing_trades', sa.Integer(), nullable=True),
        sa.Column('total_pnl', sa.DECIMAL(precision=18, scale=8), nullable=True),
        sa.Column('max_drawdown_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column('sharpe_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column('win_rate_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column('snapshot_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_account_id'), 'performance_snapshots', ['account_id'], unique=False)
    op.create_table('paper_trades',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('strategy', sa.String(), nullable=False),
        sa.Column('instrument_id', sa.String(), nullable=False),
        sa.Column('side', sa.String(), nullable=False),
        sa.Column('entry_price', sa.DECIMAL(precision=18, scale=8), nullable=False),
        sa.Column('exit_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
        sa.Column('quantity', sa.DECIMAL(precision=18, scale=8), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('pnl', sa.DECIMAL(precision=18, scale=8), nullable=True),
        sa.Column('pnl_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column('fee_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column('slippage_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column('metadata_json', sa.Text(), nullable=True),
        sa.Column('opened_at', sa.DateTime(), nullable=True),
        sa.Column('closed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_account_id'), 'paper_trades', ['account_id'], unique=False)
    op.create_table('pinned',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('instrument_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'instrument_id', name='uix_user_pinned')
    )
    op.create_index(op.f('ix_pinned_instrument_id'), 'pinned', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_pinned_user_id'), 'pinned', ['user_id'], unique=False)
    op.create_table('strategy_runs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('strategy', sa.String(), nullable=False),
        sa.Column('config_json', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('stopped_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_runs_account_id'), 'strategy_runs', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_runs_account_id'), table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_index(op.f('ix_pinned_user_id'), table_name='pinned')
    op.drop_index(op.f('ix_pinned_instrument_id'), table_name='pinned')
    op.drop_table('pinned')
    op.drop_index(op.f('ix_paper_trades_account_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_performance_snapshots_account_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_instrument_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_preferences_user_id'), table_name='preferences')
    op.drop_index(op.f('ix_preferences_key'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_paper_accounts_user_id'), table_name='paper_accounts')
    op.drop_table('paper_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
