"""phase_3_execution_foundation

Revision ID: 9cc9da229c47
Revises: 2518ca5bec17
Create Date: 2026-05-15 13:07:18.068503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc9da229c47'
down_revision: Union[str, None] = '2518ca5bec17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_capabilities',
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('supports_spot', sa.Boolean(), nullable=True),
    sa.Column('supports_perp', sa.Boolean(), nullable=True),
    sa.Column('supports_margin', sa.Boolean(), nullable=True),
    sa.Column('supports_market_order', sa.Boolean(), nullable=True),
    sa.Column('supports_limit_order', sa.Boolean(), nullable=True),
    sa.Column('supports_stop_loss', sa.Boolean(), nullable=True),
    sa.Column('supports_cancel', sa.Boolean(), nullable=True),
    sa.Column('supports_ws', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_requests_per_minute', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('exchange_name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('exchange_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('account_label', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exchange_name', 'account_label', name='uix_user_exchange_label')
    )
    with op.batch_alter_table('exchange_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('execution_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_runs_user_id'), ['user_id'], unique=False)

    op.create_table('exchange_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('passphrase_encrypted', sa.Text(), nullable=True),
    sa.Column('permissions_json', sa.Text(), nullable=True),
    sa.Column('is_testnet', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_keys_account_id'), ['account_id'], unique=False)

    op.create_table('live_trade_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('total_orders_placed', sa.Integer(), nullable=True),
    sa.Column('total_orders_filled', sa.Integer(), nullable=True),
    sa.Column('total_pnl', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_trade_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_trade_sessions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_trade_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('position_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('avg_entry_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('real_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('client_order_id', sa.String(), nullable=False),
    sa.Column('exchange_order_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('remaining_quantity', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('avg_fill_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fee_amount', sa.DECIMAL(precision=18, scale=8), nullable=True),
    sa.Column('fee_currency', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('strategy_run_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('real_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_real_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_real_orders_user_id'), ['user_id'], unique=False)

    op.create_table('risk_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('threshold_value', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('comparison', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_rules_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_rules_user_id'), ['user_id'], unique=False)

    op.create_table('order_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['real_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('risk_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_rules_account_id'))

    op.drop_table('risk_rules')
    with op.batch_alter_table('real_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_real_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_real_orders_account_id'))

    op.drop_table('real_orders')
    with op.batch_alter_table('position_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_position_snapshots_account_id'))

    op.drop_table('position_snapshots')
    with op.batch_alter_table('live_trade_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_trade_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_live_trade_sessions_account_id'))

    op.drop_table('live_trade_sessions')
    with op.batch_alter_table('exchange_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_keys_account_id'))

    op.drop_table('exchange_keys')
    with op.batch_alter_table('execution_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_runs_user_id'))

    op.drop_table('execution_runs')
    with op.batch_alter_table('exchange_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_accounts_user_id'))

    op.drop_table('exchange_accounts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    op.drop_table('connector_capabilities')
    # ### end Alembic commands ###
